import type { NarrativeEntry } from "@/types/common";

/**
 * 第四章场景一：戴家场王爷庙戏台。
 *
 * 这是一段固定镜头叙事，不开放玩家移动；声音提示保留为 cue，避免
 * 在没有经过核定的音频素材时擅自制造“史实录音”。
 */
export const CH04_WANGYE_TEMPLE_SCENE1: NarrativeEntry[] = [
	{
		entry_id: "CH04_SC01_CUE_FOOTSTEPS_CONTINUE",
		kind: "cue",
		speaker_id: "SFX",
		speaker_name: "音效",
		text: "第三章结尾的脚步声仍在继续。",
		style: "cue",
		cps: 16,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_CUE_STEPS_CONVERGE",
		kind: "cue",
		speaker_id: "SFX",
		speaker_name: "音效",
		text: "不同方向的脚步逐渐汇拢。",
		style: "cue",
		cps: 16,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_CUE_REASSEMBLE",
		kind: "cue",
		speaker_id: "SFX",
		speaker_name: "音效",
		text: "有人低声询问伤员情况，有人在确认同伴是否到齐；木棍、枪械和其他物件偶尔碰撞。",
		style: "cue",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_CUE_SOUND_RECEDE",
		kind: "cue",
		speaker_id: "SFX",
		speaker_name: "音效",
		text: "声音逐渐远去。",
		style: "cue",
		cps: 16,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_DATE",
		kind: "date",
		speaker_id: "DATE",
		text: "1927年9月11日\n戴家场王爷庙戏台",
		style: "date",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_CROWD_ESTABLISH",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "王爷庙戏台前，聚集着密集的人群。画面固定在戏台及其前方区域。",
		style: "narration",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_CROWD_FOREGROUND",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "前景里，有人扶着受伤同伴，有人抱着孩子；有人身上还沾着泥土，有人把缴获的枪械、刀矛交到戏台侧方。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_CROWD_DISTANCE",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "有人站在人群边缘，持续回头看向街口。中景和远景的人影被屋檐、庙墙和树影遮住，延伸到画面之外。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_SCALE",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "这里看不见四千余人的尽头。固定的戏台和有限的视野，只让你看见最靠近台前的一小部分。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_COUPLETS",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "戏台两侧悬着对联。晨光照在纸面上，字迹随着人群的晃动时隐时现。",
		style: "narration",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_STAGE_01",
		kind: "dialogue",
		speaker_id: "STAGE_VOICE",
		speaker_name: "戏台声音",
		text: "乡亲们，昨夜杜家团防已经被打垮！",
		style: "dialogue",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_STAGE_02",
		kind: "dialogue",
		speaker_id: "STAGE_VOICE",
		speaker_name: "戏台声音",
		text: "枪支、刀矛、粮草，全部缴获！",
		style: "dialogue",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_STAGE_03",
		kind: "dialogue",
		speaker_id: "STAGE_VOICE",
		speaker_name: "戏台声音",
		text: "杜老三负伤逃窜，已经不能再像过去那样，带着团丁进村抓人、逼租、抢地！",
		style: "dialogue",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_STAGE_04",
		kind: "dialogue",
		speaker_id: "STAGE_VOICE",
		speaker_name: "戏台声音",
		text: "杜家田地、粮仓、宅院、作坊，全部查封，由农会统一清理登记！",
		style: "dialogue",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_STAGE_05",
		kind: "dialogue",
		speaker_id: "STAGE_VOICE",
		speaker_name: "戏台声音",
		text: "杜家强占的农田，强抢的财物，还有逼着乡亲们签下的高利贷欠条，都要重新清查！",
		style: "dialogue",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_STAGE_06",
		kind: "dialogue",
		speaker_id: "STAGE_VOICE",
		speaker_name: "戏台声音",
		text: "从今往后，不能再由土豪劣绅想怎么收租，就怎么收租；想抓谁，就抓谁！",
		style: "dialogue",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_CROWD_CHEER",
		kind: "cue",
		speaker_id: "CROWD",
		speaker_name: "群众声音",
		text: "人群爆发出短促的欢呼。有人拍手，有人高喊：‘打倒杜老三！’‘好！’‘打得好！’",
		style: "cue",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_ASSOCIATION_01",
		kind: "dialogue",
		speaker_id: "STAGE_VOICE",
		speaker_name: "戏台声音",
		text: "从今天起，戴家场农民协会恢复、改组！",
		style: "dialogue",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_ASSOCIATION_02",
		kind: "dialogue",
		speaker_id: "STAGE_VOICE",
		speaker_name: "戏台声音",
		text: "推选涂济洲，担任农民协会委员长！",
		style: "dialogue",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_ASSOCIATION_03",
		kind: "dialogue",
		speaker_id: "STAGE_VOICE",
		speaker_name: "戏台声音",
		text: "成立农民自卫团！彭国材任团长！",
		style: "dialogue",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_FLAG_REVEAL",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "戏台上，两人各执一角，刷地抖开一片红。布面在风里一鼓，农会旗帜亮在众人眼前。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_APPLAUSE",
		kind: "cue",
		speaker_id: "CROWD",
		speaker_name: "群众声音",
		text: "掌声响起。它不是整齐的庆典音效，而是由前排向后方逐渐扩散。",
		style: "cue",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_ORDER",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "胜利的消息在太阳底下公之于众。武器被集中交给组织，用来放哨、巡逻，防备团防残余和地主老财的反扑。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_NEW_RULES",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "昨夜，被攻破的是一座大院；今天，王爷庙前立下新的规矩：谁来管，谁来守，遇事找谁决断。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC01_END",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "这场暴动还没有结束。它正在从一次夜袭，变成一组白天黑夜都要维持的秩序。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
];
