import type { NarrativeEntry } from "@/types/common";

/**
 * 第四章场景三：从王爷庙回到现代实践驻地。
 *
 * 这一段仍是固定镜头叙事，不把现代场景重新做成可探索地图；地图由
 * 序章实践驻地的原始底图复用，叙事文字负责把“醒来”的感官差异交代清楚。
 */
export const CH04_MODERN_RETURN_NARRATIVE: NarrativeEntry[] = [
	{
		entry_id: "CH04_SC03_CUE_PEN_DROP",
		kind: "cue",
		speaker_id: "SFX",
		speaker_name: "音效",
		text: "王爷庙的人群声突然被一声笔落在桌面的声音中断。",
		style: "cue",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_BLACKOUT",
		kind: "cue",
		speaker_id: "SFX",
		speaker_name: "黑幕",
		text: "黑幕。",
		style: "cue",
		cps: 18,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_CUE_FAN",
		kind: "cue",
		speaker_id: "SFX",
		speaker_name: "音效",
		text: "风扇转动声出现。",
		style: "cue",
		cps: 16,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_CUE_PAPERS",
		kind: "cue",
		speaker_id: "SFX",
		speaker_name: "音效",
		text: "纸张被风吹动。",
		style: "cue",
		cps: 16,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_CUE_COMPUTER",
		kind: "cue",
		speaker_id: "SFX",
		speaker_name: "音效",
		text: "远处有电脑运行的低鸣声。",
		style: "cue",
		cps: 15,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_DATE",
		kind: "date",
		speaker_id: "DATE",
		text: "现代\n实践驻地",
		style: "date",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_WAKE",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "你伏在桌边醒来。一只手压着摊开的材料，另一只手垂在桌边。脸颊上有纸张留下的压痕。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_BODY_MEMORY",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "手臂麻木，肩膀和手掌仍然残留着酸痛感，好像刚撞开一扇大门。桌面平整、干燥。台灯比中秋月刺眼。",
		style: "narration",
		cps: 12,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_REALITY_CHECK",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "脚上没沾泥，耳边没有爆响，眼前没有王爷庙前拥挤的人群。",
		style: "narration",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_PAGE_FOUND",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "你抬起头。风扇将桌上的纸页吹动。有一页停在关于杜家大院的材料上。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_PAGE_TEXT",
		kind: "narration",
		speaker_id: "DOCUMENT",
		speaker_name: "材料",
		text: "1927年9月10日，戴家场暴动。\n杜家团防被击溃。\n杜老三负伤逃窜。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_PAGE_GAZE",
		kind: "thought",
		speaker_id: "PLAYER_THOUGHT",
		speaker_name: "心理描写",
		avatar_id: "prologue-player",
		text: "你的视线停在“负伤逃窜”几个字上。",
		style: "thought",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_MEMORY_STEPS",
		kind: "thought",
		speaker_id: "PLAYER_THOUGHT",
		speaker_name: "心理描写",
		avatar_id: "prologue-player",
		text: "中秋夜，月光下，暗处步履不停，脚步窸窣。\n杜家榨房起火照亮了半边天，街面爆响如雷。",
		style: "thought",
		cps: 11,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_MEMORY_FIRE",
		kind: "thought",
		speaker_id: "PLAYER_THOUGHT",
		speaker_name: "心理描写",
		avatar_id: "prologue-player",
		text: "浓烟、烈火、三面队伍瓮中捉鳖。王爷庙里，人们欢呼杜家团防被打垮。",
		style: "thought",
		cps: 11,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_MEMORY_PEOPLE",
		kind: "thought",
		speaker_id: "PLAYER_THOUGHT",
		speaker_name: "心理描写",
		avatar_id: "prologue-player",
		text: "有人询问被强占的田地和欠条，有人把缴获的武器交给自卫团。",
		style: "thought",
		cps: 12,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC03_MEMORY_PAPER",
		kind: "thought",
		speaker_id: "PLAYER_THOUGHT",
		speaker_name: "心理描写",
		avatar_id: "prologue-player",
		text: "现在，这些事情只剩下纸面上的几行字。\n纸面很安静。\n安静得像是什么都没有发生过。",
		style: "thought",
		cps: 11,
		advance: "manual",
	},
];
